// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy6XESVLAAoS7cV8AkwZnI6qIv6nKeOjE',
    appId: '1:540640109451:web:cad8558244ba638ce4858e',
    messagingSenderId: '540640109451',
    projectId: 'travel-planner-a5c3b',
    authDomain: 'travel-planner-a5c3b.firebaseapp.com',
    storageBucket: 'travel-planner-a5c3b.appspot.com',
    measurementId: 'G-RMNMY1YLBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUxqI3yCVd_Rd0FxXfbU35iUqaIAdIR-Y',
    appId: '1:540640109451:android:16a7b3fe627ed90be4858e',
    messagingSenderId: '540640109451',
    projectId: 'travel-planner-a5c3b',
    storageBucket: 'travel-planner-a5c3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB60NoRcvudFv0tAXbyZF405rd96vSErQk',
    appId: '1:540640109451:ios:3382588039e5894be4858e',
    messagingSenderId: '540640109451',
    projectId: 'travel-planner-a5c3b',
    storageBucket: 'travel-planner-a5c3b.appspot.com',
    iosBundleId: 'com.example.travelPlannerY3g13',
  );
}
